### ISSUE TITLE
Cannot click banner

### ISSUE THREAD

**Issue by purepure** [OrigameStudio/admob-unity-plugin#1]
I integrate this libs and success in showing the adv in a banner, but when I try to click that banner, nothing happen. It seem the banner cannot detect touch event

Please fix its because it will leak so many money from developer

**Comment by guillermocalvo** [comment]
The plugin does not control touch events; the banner is simply an Android Activity. It is created by the AdMob library and it takes care of clicks by itself.

Please note that AdMob prohibits and monitors _fake clicks_: if you are testing your app, you **must** use "test mode", otherwise AdMob may stop serving banners, or even disable your account. Please read [the plugin documentation](https://github.com/guillermocalvo/admob-unity-plugin#test-mode).

Have you checked your log file? Maybe AdMob is preventing you from clicking your own banners. You can watch logs in real time by using [Android Debug Bridge](http://developer.android.com/tools/help/adb.html).

I've been using this plugin for some time to show banners in my apps, and they do detect touch events. Also, other developers are currently using the plugin and it's working for them.

If you still believe this is plugin's fault, please provide logs and a sample app which does not work, so I can try and reproduce the error. Source code would be helpful, too.

**Comment by purepure** [comment]
I work with admob so long and I understand I need to use "test mode" to prevent block account. I think this is not problem of my account is disable (because it still available. My friend got same issue like this).
I try to search around and found this: 
http://forum.unity3d.com/threads/195169-Google-Admob-plugin-for-Unity-ad-is-not-clickable

I work for me. By this way, we need to add this line: 
meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="true"
under "com.unity3d.player.UnityPlayerProxyActivity" activity.

**Comment by guillermocalvo** [comment]
Oh, I see. It was an issue regarding Unity player... I guess my apps work because I compiled them with a different version of Unity than yours.

Thanks for sharing this workaround; I'll add that to the sample Unity project provided on this repository.

**Comment by purepure** [comment]
Sorry guy, me again!
After fixed the plugin as the workaround, I can click the banner, but it not navigate/open the advertisement. (I mean when I click the banner, it received click event but do nothing)
are there are someone around here got same issue?. Please have a check 

Thank so much

**Comment by AshishG24** [comment]
for AdMob Banner ads non clickable: 
(Try This Hope its helpful for you)

first of all make sure these simple points:
1. Check Your Layout Arrangements. May be Some other Layouts overlaps the ad container.So when you click it clicks the overlapped layout components.
2. Make sure the ad is active/ enabled in your AdMob account. As I remember it shows colour green when active.
3. if necessary. Try creating another ad unit and add the ad again.

If all Set then check this:

In Unity3D 4.XX your current Assets folder for your game go to

Plugins > Android > AndroidManifest.xml

In the Manifest

under the application >> activity

you can find UnityPlayer "NativeEvents" by default its "false"

like this:

< meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="false" />

so change it to "true"

< meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="true" />

and Save it and make build, that's all..

It's worked for me. :)

**Comment by caodinhhuy** [comment]
@AshishG24 My project has a same problem, but I can not found AndroidManifest.xml in _Plugins > Android_ folder.
In child folder "_Plugins > Android > GoogleMobileAdsPlugin_" I found a AndroidManifest.xml, I add above meta to this file but it not work. I still can not click to banner.
How I can find main AndroidManifest.xml file?
